travis:
  secure:
    BINSTAR_TOKEN: tN6pHz+77ER+1vqrOUrh6mPQB+QHo8K/vTkjt011psDuOxY2a5X2fCj841ZnIpp+TL/f74IKFsrukEB5Yli6Wv4mzw+mjW0aqrregOPryMB76rAL9BtKzU680LflCy4TySASvQI6S9rPJbIqVTZZiGwWoY4iSpMFyAXlEguj2WPJJPyUcCKGVj4uAc0o8epuQ0u6gO9poftIM5WFrjrhPlzUKXfGyPVfMVxAuiOhsrkHQpXb4D1uknVtCr5ihDGeAuzOKjj8NRQmi+vFdqMIDeVKmT3r3ip9wvdTzYQ0UQSaj/ssy4R0Bj+w00z9Qk2wUwtJLUNVQeyspaIXJFfXX3AFQNp6VBNuXwzXS6vGs/Qpmt47GZTGJAXh37Drn28qwJFE/VDVUTw1vZeUqrXSn43QsuGSIet3TFmXMB1bgDYWj5U0H/MT8CSlkO3L2MvizYBvmoi8TKj2vN3RBLppQKql4gpQa0W8eVG3+L3mB4d3Hwlv56GFWOyI5mBLK1dGP5djI/fOUlrHxn9Ec6AvJ0ka1P9H8WZfD1bOm9h49P/GJtY2SmINdlMRIot0NMbsDfXhF8yxVySW/60M88pbxqCh2jIuqkZj8E3Xa4bVE+1Ipm0lar0KLw+7YOUSkPlx/CF5b9tWGFXeRBQauqe4UU4394E8a37Fwuz9NyqPY+s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
